### PR TITLE
Use session storage for save path

### LINKED ISSUE #586: ChaiNNer loses name of current file on reload
~If you hit a runtime error while running a chain in a chain that you have already saved, the filename in the header will revert to unnamed and Save will require you to Save As, because the association between the chain and the file gets broken.~

Using View -> Reload causes chain to lose association to its filename, the header reverts to "Untitled", and Save As is required to save chain again.

### PR DESCRIPTION
**Pull request by joeyballentine**
Fixes #586

### CODE REVIEW

**Comment by RunDevelopment** [comment]
How will this affect the saved-change status? If I make changes to a file and reload, will Chainner forget that I made changes? Before this PR, this wasn't a problem, but it might be now.

**Comment by joeyballentine** [comment]
> How will this affect the saved-change status? If I make changes to a file and reload, will Chainner forget that I made changes? Before this PR, this wasn't a problem, but it might be now.

it's actually the opposite. If you have no changes and reload, it will think you have changes. similarly, if you have changes it will still think you have changes, but that's probably just due to it always thinking you have unsaved changes on reload.

I guess this is fine?

File: src/renderer/hooks/useSessionStorage.ts [hunk 1]
```diff
@@ -1,11 +1,19 @@
...
+    }
+};
+
 export const getSessionStorageOrDefault = <T>(key: string, defaultValue: T): T => {
     const stored = sessionStorage.getItem(key);
     if (!stored) {
         return defaultValue;
     }
-    return JSON.parse(stored) as T;
+    return safeJsonParse(stored) as T;
```
Comment (RunDevelopment) [inline src/renderer/hooks/useSessionStorage.ts:16]: How could there ever be invalid JSON in there?

Comment (joeyballentine) [reply src/renderer/hooks/useSessionStorage.ts:16]: the string "undefined" apparently does not like being json parsed

Comment (joeyballentine) [reply src/renderer/hooks/useSessionStorage.ts:16]: remove this and you'll crash when you reload (without having a file opened/saved)

Comment (RunDevelopment) [reply src/renderer/hooks/useSessionStorage.ts:16]: Well, that's because you are using `useSessionStorage` incorrectly. This hook only supports JSON values, and `undefined` is not a JSON value. Use `null` instead.

Comment (joeyballentine) [reply src/renderer/hooks/useSessionStorage.ts:16]: I still think it would be good to wrap the json parse around this. If you ever somehow get an invalid state in your session, it'll just continue to crash without a way to fix it (which is very bad)

Comment (RunDevelopment) [reply src/renderer/hooks/useSessionStorage.ts:9]: With this "fix", the JSON parse won't crash anymore, yes. Now the first consumer of the returned value will crash because `undefined` is guaranteed to not be returned by the API. With this fix, the API lies.

Comment (RunDevelopment) [reply src/renderer/hooks/useSessionStorage.ts:9]: Same for `null`. The consumer controls the `T`, not `useSession`.

Comment (RunDevelopment) [reply src/renderer/hooks/useSessionStorage.ts:9]: @joeyballentine

Comment (joeyballentine) [reply src/renderer/hooks/useSessionStorage.ts:9]: I'll get rid of it then
